/** Shared PostSoma core and NewsNow's signal-reading attachments. */
export const mascotConfig = {
  version: "3.0.0-news-hub",
  storageKey: "postsoma-news-hub-mascot-v3",
  core: {
    light: "/mascot/core/plate_light.png",
    dark: "/mascot/core/plate_dark.png",
    width: 1122,
    height: 1228,
    sprout: {
      light: "/mascot/core/sprout_light.png",
      dark: "/mascot/core/sprout_dark.png",
      left: "43.94%",
      top: "0%",
      displayWidth: "12.03%",
      displayHeight: "11.16%",
      pivot: "48.74% 85.4%",
    },
    eyes: [
      { x: 728.9, y: 563.8, moonRadius: 48.6, haloRadius: 66 },
      { x: 382.7, y: 563.9, moonRadius: 48.6, haloRadius: 66 },
    ],
  },
  slots: {
    paper: {
      light: "/mascot/skins/news-hub/paper_clean.png",
      dark: "/mascot/skins/news-hub/paper_dark.png",
      left: "20%", top: "48%", width: "32%", zIndex: 3,
      pivot: "50% 50%",
      behavior: { follow_breath: true, on_click: "page_turn", on_shock: "rattle" },
    },
    signal: {
      light: "/mascot/skins/news-hub/signal_clean.png",
      dark: "/mascot/skins/news-hub/signal_dark.png",
      right: "4%", top: "6%", width: "18%", zIndex: 4,
      pivot: "50% 50%",
      behavior: { follow_breath: true, on_idle: "receive_pulse", pulseMs: 1100, pulseMin: 0.92, pulseMax: 1.12, on_click: "ping", on_shock: "rattle", on_antic: "signal_scan" },
    },
  },
  behaviorWheel: [
    { id: "sprout_sway", weight: 40, durationMs: 3_500 },
    { id: "peek_curious", weight: 30, durationMs: 1_800 },
    { id: "wander_slide", weight: 20, durationMs: 4_500 },
    { id: "subtle_tilt", weight: 10, durationMs: 1_200 },
  ],
  siteAntic: {
    id: "signal_scan",
    minimumIdleMs: 20_000,
    cooldownMs: 20_000,
    chance: 0.16,
    durationMs: 1_400,
  },
  scheduler: {
    tickMs: 100,
    heartbeatMs: 1_000,
    durationDrift: 0.2,
    firstActionMs: 4_500,
    idleGapMinMs: 1_400,
    idleGapMaxMs: 2_800,
    tapWindowMs: 320,
    activeIdleMs: 10_000,
    sleepAfterMs: 90_000,
    hoverMs: 560,
    clickMs: 760,
    flinchMs: 480,
    blushMs: 980,
    shyHideMs: 650,
    shyHiddenMs: 2_400,
    shyQuietMs: 2_000,
    alertMs: 900,
    scrollThresholdPx: 360,
    rapidPointerSpeedPxPerSecond: 900,
    nearbyRadiusPx: 150,
    minimumAlertGapMs: 1_800,
  },
  motion: {
    stage: { mobile: { width: 118, height: 129 }, desktop: { width: 132, height: 145 } },
    restOffsetPx: { mobile: 81, desktop: 91 },
    peekOffsetPx: { mobile: 67, desktop: 77 },
    hiddenOffsetPx: { mobile: 160, desktop: 176 },
    companionBottom: "max(16px, env(safe-area-inset-bottom, 16px))",
    minHorizontalPercent: 16,
    maxHorizontalPercent: 84,
    startHorizontalPercent: 78,
    wanderMinPercent: 16,
    wanderMaxPercent: 84,
    wanderMinStepPercent: 16,
    wanderMaxStepPercent: 32,
  },
  drives: {
    defaults: { energy: 80, curiosity: 60, affection: 40 },
    energyDecayPerMinute: 1.5,
    curiosityDecayPerMinute: 2,
    affectionDecayPerMinute: 1,
    sleepRecoveryPerMinute: 10,
    hoverAffection: 8,
    clickAffection: 15,
    nearbyCuriosity: 10,
  },
  priorities: { autonomous: 0, environment: 1, direct: 2 },
} as const;

export type MascotBehaviorId = (typeof mascotConfig.behaviorWheel)[number]["id"] | typeof mascotConfig.siteAntic.id;
export default mascotConfig;
